[package]
name = "rustserver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = {version = "1.0.219" , features = ["derive"]}
tokio = {version = "1.47.1" , features = ["full"]}
